# COMPLETE THIS FILE
services:
  web:
    build: ./web
    image: saaddak77/tripmeal-web:v1
    ports:
      - "3000:5000"
    env_file:
      - tripmeal.env
    depends_on:
      - db
    networks:
      - tripmeal_network
    restart: unless-stopped

  db:
    build: ./database
    image: saaddak77/tripmeal-db:v1
    env_file:
      - tripmeal.env
    volumes:
      - data_tripmeal:/var/lib/mysql
    networks:
      - tripmeal_network
    restart: unless-stopped

volumes:
  data_tripmeal:

networks:
  tripmeal_network: